name: "Push/Pull Request Docs Build"
on: 
- pull_request
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:    
    - name: Set up Python3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        args: "docs/"
    - uses: ammaraskar/sphinx-action@master
      with:
        args: "docs/"
