name: "Push/Pull Request Docs Build"
on: 
- pull_request
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.5'
    - uses: ammaraskar/sphinx-action@master
      with:
        args: "docs/"
    - uses: ammaraskar/sphinx-action@master
      with:
        args: "docs/"
