name: "Pull Request Docs Check"
on: 
- pull_request
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install numpy
      run: >-
        python -m
        pip install
        numpy
    - uses: ammaraskar/sphinx-action@master
      with:
        args: "docs/"
